email_data = [
    {"subject": "Meeting Reminder: Q4 Sales Review at 3 PM", "type": "normal"},
    {"subject": "Invoice #2345 Paid Successfully", "type": "normal"},
    {"subject": "Welcome to [Platform]! Confirm Your Email", "type": "normal"},
    {"subject": "Your Amazon Order Has Been Shipped", "type": "normal"},
    {"subject": "Team Lunch: Friday, 12 PM at the Cafeteria", "type": "normal"},
    {"subject": "Your Upcoming Flight Itinerary", "type": "normal"},
    {"subject": "Performance Review Scheduled for Next Week", "type": "normal"},
    {"subject": "Company Newsletter: November Edition", "type": "normal"},
    {"subject": "System Update: Maintenance Scheduled on Saturday", "type": "normal"},
    {"subject": "Happy Birthday! Here's a Gift Just for You", "type": "normal"},
    {"subject": "Your Package Has Been Delivered", "type": "normal"},
    {"subject": "Tax Filing Confirmation", "type": "normal"},
    {"subject": "Password Changed Successfully", "type": "normal"},
    {"subject": "Holiday Greetings from Our CEO", "type": "normal"},
    {"subject": "Job Application Received - Thank You!", "type": "normal"},
    {"subject": "New Feature Update: Try It Now!", "type": "normal"},
    {"subject": "Your Subscription Is Active", "type": "normal"},
    {"subject": "Payment Receipt for Invoice #67890", "type": "normal"},
    {"subject": "Meeting Agenda: Monday, 9 AM", "type": "normal"},
    {"subject": "Congratulations on Your Promotion!", "type": "normal"},
    {"subject": "Exclusive Offer for Our Valued Customers", "type": "normal"},
    {"subject": "Your Monthly Bank Statement Is Ready", "type": "normal"},
    {"subject": "Update Your Profile for Better Recommendations", "type": "normal"},
    {"subject": "Staff Meeting Postponed to Tuesday", "type": "normal"},
    {"subject": "Quarterly Report: Please Review by Friday", "type": "normal"},
    {"subject": "Appointment Confirmation for [Service]", "type": "normal"},
    {"subject": "Join Our Webinar: Learn the Latest Trends", "type": "normal"},
    {"subject": "Your Refund Has Been Processed", "type": "normal"},
    {"subject": "Important: Office Closed on Public Holiday", "type": "normal"},
    {"subject": "Exclusive Invitation to Our VIP Event", "type": "normal"},
    {"subject": "Survey Reminder: Share Your Feedback", "type": "normal"},
    {"subject": "Health Checkup Scheduled for Thursday", "type": "normal"},
    {"subject": "Your Rental Application Has Been Approved", "type": "normal"},
    {"subject": "Welcome to the Team: Orientation Details Inside", "type": "normal"},
    {"subject": "Your Library Book Is Due Soon", "type": "normal"},
    {"subject": "Travel Insurance Policy Confirmation", "type": "normal"},
    {"subject": "Thank You for Your Donation!", "type": "normal"},
    {"subject": "New Course Available: Enroll Today", "type": "normal"},
    {"subject": "Your Rewards Points Are About to Expire", "type": "normal"},
    {"subject": "Update: Office Renovation Schedule", "type": "normal"},
    {"subject": "Join Us for a Virtual Town Hall Meeting", "type": "normal"},
    {"subject": "Event Registration Confirmed: See You Soon!", "type": "normal"},
    {"subject": "Your Digital Receipt for Purchase #9876", "type": "normal"},
    {"subject": "Your Reservation Is Confirmed", "type": "normal"},
    {"subject": "Monthly Fitness Challenge Starts Monday!", "type": "normal"},
    {"subject": "Your Order Is Ready for Pickup", "type": "normal"},
    {"subject": "IT Support Ticket Resolved Successfully", "type": "normal"},
    {"subject": "Weekly Update: Latest News and Announcements", "type": "normal"},
    {"subject": "Reminder: Project Submission Due Tomorrow", "type": "normal"},
    {"subject": "Your Membership Has Been Renewed", "type": "normal"},
    {"subject": "Reminder: Team Outing This Friday", "type": "normal"},
    {"subject": "Share Your Experience: Leave a Review", "type": "normal"},
    {"subject": "Thank You for Attending Our Event!", "type": "normal"},
    {"subject": "Exclusive Access: Early Bird Discounts Inside", "type": "normal"},
    {"subject": "Happy Anniversary! Celebrate With a Special Gift", "type": "normal"},
    {"subject": "Please Update Your Payment Method", "type": "normal"},
    {"subject": "Your Loan Application Is Approved", "type": "normal"},
    {"subject": "We're Excited to See You at the Workshop", "type": "normal"},
    {"subject": "Class Schedule for the Upcoming Semester", "type": "normal"},
    {"subject": "Your Ticket to [Event Name] Is Confirmed", "type": "normal"},
    {"subject": "Time to Vote: Employee Polls Are Open", "type": "normal"},
    {"subject": "Your Certificate of Completion Is Ready", "type": "normal"},
    {"subject": "New Office Policies Effective from Next Month", "type": "normal"},
    {"subject": "Employee Spotlight: Meet Our Star Performer", "type": "normal"},
    {"subject": "Holiday Party Invitation: RSVP Now", "type": "normal"},
    {"subject": "Your Leave Request Has Been Approved", "type": "normal"},
    {"subject": "Flash Sale: Save 50% Today Only!", "type": "normal"},
    {"subject": "Reminder: Vaccination Drive at the Office", "type": "normal"},
    {"subject": "Your Weekly Performance Report", "type": "normal"},
    {"subject": "Thank You for Your Support!", "type": "normal"},
    {"subject": "Congratulations: You've Been Nominated for [Award]", "type": "normal"},
    {"subject": "Your Feedback Matters: Take Our Quick Survey", "type": "normal"},
    {"subject": "Join Us for a Fireside Chat With Industry Leaders", "type": "normal"},
    {"subject": "Happy Holidays From All of Us at [Company]", "type": "normal"},
    {"subject": "Friendly Reminder: Stay Safe Online", "type": "normal"},
    {"subject": "Your Health Benefits Have Been Updated", "type": "normal"},
    {"subject": "New Project Assigned: Details Inside", "type": "normal"},
    {"subject": "Year-End Financial Report Now Available", "type": "normal"},
    {"subject": "Your Certificate of Excellence Awaits", "type": "normal"},
    {"subject": "Let's Celebrate: Office Anniversary Party", "type": "normal"},
    {"subject": "Invitation: Career Growth Workshop", "type": "normal"},
    {"subject": "Congratulations on Completing 5 Years!", "type": "normal"},
    {"subject": "Your Flight Booking Has Been Confirmed", "type": "normal"},
    {"subject": "Exclusive Sneak Peek: [Product Name]", "type": "normal"},
    {"subject": "Take Control of Your Finances: Tips Inside", "type": "normal"},
    {"subject": "Thank You for Your Partnership", "type": "normal"},
    {"subject": "Download Your Monthly Statement", "type": "normal"},
    {"subject": "Your Feedback Earned You a Reward!", "type": "normal"},
    {"subject": "Friendly Reminder: Pay Your Dues Before [Date]", "type": "normal"},
    {"subject": "Important Announcement: Office Relocation", "type": "normal"},
    {"subject": "Welcome Back: We've Missed You!", "type": "normal"},
    {"subject": "Stay Informed: Monthly Security Tips", "type": "normal"},
    {"subject": "Exciting News: We're Launching Something New", "type": "normal"},
    {"subject": "Special Thanks From the [Organization Name]", "type": "normal"},
    {"subject": "Don't Forget: Weekly Team Meeting Tomorrow", "type": "normal"},
    {"subject": "Your New Password Has Been Set Successfully", "type": "normal"},
    {"subject": "Reminder: Compliance Training Due Soon", "type": "normal"},
    {"subject": "Your Opinion Is Valuable: Share It Now", "type": "normal"},
    {"subject": "Your Account Has Been Suspended: Verify Now", "type": "phishing"},
    {"subject": "Congratulations! You've Won a $10,000 Gift Card", "type": "phishing"},
    {"subject": "Urgent: Reset Your Password to Secure Your Account", "type": "phishing"},
    {"subject": "Act Now: Claim Your Unclaimed Funds", "type": "phishing"},
    {"subject": "Verify Your Bank Details for Immediate Access", "type": "phishing"},
    {"subject": "Notice of Legal Action Against You", "type": "phishing"},
    {"subject": "You Have Been Shortlisted for a High-Paying Job", "type": "phishing"},
    {"subject": "Final Notice: Lottery Winning Claim Expiring Soon", "type": "phishing"},
    {"subject": "Charity Appeal: Help Disaster Victims Today", "type": "phishing"},
    {"subject": "Your Computer Has Been Compromised: Fix It Now", "type": "phishing"},
    {"subject": "Unusual Activity Detected on Your Account", "type": "phishing"},
    {"subject": "Payment Required to Reactivate Subscription", "type": "phishing"},
    {"subject": "Unlock Exclusive Benefits by Updating Your Details", "type": "phishing"},
    {"subject": "Your Tax Refund Is Waiting: Click to Claim", "type": "phishing"},
    {"subject": "Pay Outstanding Balance to Avoid Service Disruption", "type": "phishing"},
    {"subject": "Your Social Media Account Has Been Flagged", "type": "phishing"},
    {"subject": "Security Alert: Verify Identity to Avoid Suspension", "type": "phishing"},
    {"subject": "Free iPhone 15 Pro for First 100 Respondents", "type": "phishing"},
    {"subject": "Urgent: Confidential Document Needs Your Review", "type": "phishing"},
    {"subject": "Claim Your Complimentary Vacation Package", "type": "phishing"},
    {"subject": "Verify Your Purchase of [Expensive Item]", "type": "phishing"},
    {"subject": "Action Required: Update Payment Information", "type": "phishing"},
    {"subject": "Complete This Survey to Receive a $50 Gift Card", "type": "phishing"},
    {"subject": "Important: Pay $200 to Remove Malware", "type": "phishing"},
    {"subject": "Immediate Action Required: Verify Your Billing Address", "type": "phishing"},
    {"subject": "You’ve Been Gifted a Free Cryptocurrency Token", "type": "phishing"},
    {"subject": "Warning: Failed Login Attempt on Your Account", "type": "phishing"},
    {"subject": "Congratulations! Your Loan Is Pre-Approved", "type": "phishing"},
    {"subject": "Urgent Update: Suspicious Login Detected", "type": "phishing"},
    {"subject": "Act Fast: Special Promotion Ends Tonight", "type": "phishing"},
    {"subject": "Secure Your Bank Account Immediately", "type": "phishing"},
    {"subject": "Limited-Time Offer: Upgrade to Premium Today", "type": "phishing"},
    {"subject": "Your Parcel Is on Hold: Provide Details to Deliver", "type": "phishing"},
    {"subject": "Exclusive Investment Opportunity Available Now", "type": "phishing"},
    {"subject": "Urgent: Your Card Has Been Declined", "type": "phishing"},
    {"subject": "Claim Your Free Antivirus Subscription", "type": "phishing"},
    {"subject": "Your Online Banking Session Has Expired", "type": "phishing"},
    {"subject": "Congratulations! You’ve Been Selected for a Prize", "type": "phishing"},
    {"subject": "Subscription Renewal Required to Avoid Cancellation", "type": "phishing"},
    {"subject": "Verify Your Account Ownership Immediately", "type": "phishing"},
    {"subject": "Your Application Has Been Approved", "type": "phishing"},
    {"subject": "Action Required: Update Security Information", "type": "phishing"},
    {"subject": "Claim Your Free Vacation to Hawaii", "type": "phishing"},
    {"subject": "Exclusive Offer: Earn $5,000 in a Month", "type": "phishing"},
    {"subject": "Verify This Transaction: [$500 Payment]", "type": "phishing"},
    {"subject": "Your PayPal Account Is at Risk", "type": "phishing"},
    {"subject": "Download Invoice for Outstanding Payment", "type": "phishing"},
    {"subject": "Thank You for Your Order: Payment Pending", "type": "phishing"},
    {"subject": "Final Reminder: Upgrade Your Account Today", "type": "phishing"},
    {"subject": "Secure Your Digital Wallet Now", "type": "phishing"},
    {"subject": "Protect Your Account From Fraud: Verify Now", "type": "phishing"},
    {"subject": "Special Reward Awaits: Claim Your Gift", "type": "phishing"},
    {"subject": "Your Delivery Has Been Delayed: Update Address", "type": "phishing"},
    {"subject": "Recover Lost Files With Our New Service", "type": "phishing"},
    {"subject": "Important Update: Verify Before Midnight", "type": "phishing"},
    {"subject": "Free Webinar: Learn How to Get Rich Quick", "type": "phishing"},
    {"subject": "Your Account May Be Deactivated Soon", "type": "phishing"},
    {"subject": "Last Chance: Claim Your Exclusive Bonus", "type": "phishing"},
    {"subject": "Suspicious Activity Detected: Review Transaction", "type": "phishing"},
    {"subject": "Earn $1,000 by Signing Up Today", "type": "phishing"},
    {"subject": "Your Ticket to Financial Freedom Awaits", "type": "phishing"},
    {"subject": "Confirm Your Email to Unlock Your Rewards", "type": "phishing"},
    {"subject": "Payment Required: Renew Your Subscription Now", "type": "phishing"},
    {"subject": "Activate Your Lifetime Warranty Immediately", "type": "phishing"},
    {"subject": "Pay Outstanding Invoice to Avoid Late Fees", "type": "phishing"},
    {"subject": "Immediate Action Needed: Verify Identity", "type": "phishing"},
    {"subject": "You Have Been Selected for a Mystery Shopper Job", "type": "phishing"},
    {"subject": "Unblock Your Account: Verify Login Activity", "type": "phishing"},
    {"subject": "Congratulations! You’re Eligible for a Loan", "type": "phishing"},
    {"subject": "Confirm Your Details to Avoid Account Suspension", "type": "phishing"},
    {"subject": "Your Data Has Been Compromised: Download Fix", "type": "phishing"},
    {"subject": "Claim Your Free Gift by Completing This Survey", "type": "phishing"},
    {"subject": "Important: Update Your Tax Information", "type": "phishing"},
    {"subject": "Your Prize Is Waiting: Act Now to Claim", "type": "phishing"},
    {"subject": "Your Bank Account Requires Verification", "type": "phishing"},
    {"subject": "Get 70% Off on Premium Services Today", "type": "phishing"},
    {"subject": "Unusual Activity on Your Social Media Account", "type": "phishing"},
    {"subject": "Confirm Your Attendance for Exclusive Event", "type": "phishing"},
    {"subject": "You’ve Won a Trip to the Maldives!", "type": "phishing"},
    {"subject": "Suspension Notice: Reactivate Your Account", "type": "phishing"},
    {"subject": "Your Account Is Under Review: Verify Now", "type": "phishing"},
    {"subject": "Your Credit Card Details Need Updating", "type": "phishing"},
    {"subject": "Warning: Virus Detected on Your Device", "type": "phishing"},
    {"subject": "You’ve Been Selected for a Business Opportunity", "type": "phishing"},
    {"subject": "Action Required: Review Pending Payment", "type": "phishing"},
    {"subject": "Your Free Subscription Ends Tomorrow", "type": "phishing"},
    {"subject": "Claim $1,000 by Joining Our Program", "type": "phishing"},
    {"subject": "Warning: Your Account May Be Hacked", "type": "phishing"},
    {"subject": "Update Required to Secure Your Device", "type": "phishing"},
    {"subject": "Special Offer Just for You: 90% Off", "type": "phishing"},
    {"subject": "Free Trial Expires Today: Upgrade Now", "type": "phishing"},
    {"subject": "Verify This Payment to Avoid Decline", "type": "phishing"},
    {"subject": "Protect Your Account by Verifying Details", "type": "phishing"},
    {"subject": "Complete Your Registration for a Free Gift", "type": "phishing"},
    {"subject": "Your Social Security Number May Be Stolen", "type": "phishing"},
    {"subject": "Win Big: Participate in Our Sweepstakes", "type": "phishing"},
    {"subject": "Update Your Account Settings", "type": "phishing"},
    {"subject": "Account Security Alert: Take Action Now", "type": "phishing"},
    {"subject": "Earn Up to $5,000 a Month With This Opportunity", "type": "phishing"},
    {"subject": "Confirm Your Participation in Our Exclusive Program", "type": "phishing"},
    {"subject": "Your Payment Is Declined: Resolve It Now", "type": "phishing"},
    {"subject": "Fraud Alert: Unusual Transactions Detected", "type": "phishing"},
    {"subject": "Your Computer Is Infected: Download Fix Now", "type": "phishing"},
    {"subject": "Exclusive Access to the Latest Investment Scheme", "type": "phishing"},
    {"subject": "Act Now: Your Subscription Renewal Is Pending", "type": "phishing"},
    {"subject": "Congratulations! You’ve Won a Year of Free Services", "type": "phishing"},
    {"subject": "Recover Your Forgotten Password Immediately", "type": "phishing"},
    {"subject": "Important: Secure Your Bank Account Now", "type": "phishing"},
    {"subject": "Final Reminder: Update Your Payment Details", "type": "phishing"},
    {"subject": "Suspension Warning: Verify Your Identity", "type": "phishing"},
    {"subject": "Urgent: Your Account Has Been Locked", "type": "phishing"},
    {"subject": "Claim Your Free Trial of Our Premium Service", "type": "phishing"},
    {"subject": "Secure Your Credit Card From Unauthorized Use", "type": "phishing"},
    {"subject": "Verify This Payment of $499 to Proceed", "type": "phishing"},
    {"subject": "Alert: Your Tax Refund Is About to Expire", "type": "phishing"},
    {"subject": "Special Reward: Claim Your Gift Card Today", "type": "phishing"},
    {"subject": "Your Email Account Needs Verification", "type": "phishing"},
    {"subject": "Congratulations! You’ve Been Approved for a Loan", "type": "phishing"},
    {"subject": "Unlock Exclusive Benefits by Confirming Details", "type": "phishing"},
    {"subject": "Important: Review Your Account Transactions", "type": "phishing"},
    {"subject": "Your Account May Be at Risk: Take Action Now", "type": "phishing"},
    {"subject": "Claim Your Prize Before It’s Too Late", "type": "phishing"},
    {"subject": "Verify Your Address to Complete Delivery", "type": "phishing"},
    {"subject": "Exclusive Offer: Sign Up for 75% Off", "type": "phishing"},
    {"subject": "Update Your Account to Continue Using Services", "type": "phishing"},
    {"subject": "Final Notice: Outstanding Invoice Payment Due", "type": "phishing"},
    {"subject": "Win a Free Cruise by Entering Our Contest", "type": "phishing"},
    {"subject": "Secure Your Data With Our New App", "type": "phishing"},
    {"subject": "Your Device Is at Risk: Download Security Patch", "type": "phishing"},
    {"subject": "Congratulations! You’ve Won a New Car!", "type": "phishing"},
    {"subject": "Your Bank Account Is Temporarily Locked", "type": "phishing"},
    {"subject": "Update Your Account for Continued Access", "type": "phishing"},
    {"subject": "Recover Lost Files by Downloading Our Tool", "type": "phishing"},
    {"subject": "Alert: Unusual Login Detected on Your Account", "type": "phishing"},
    {"subject": "Renew Your Subscription Before It Expires", "type": "phishing"},
    {"subject": "Claim Your Reward Points Before They Expire", "type": "phishing"},
    {"subject": "Your Account Has Been Locked: Verify Identity", "type": "phishing"},
    {"subject": "Win Big by Completing This Quick Survey", "type": "phishing"},
    {"subject": "Congratulations! You’ve Been Selected for a Prize", "type": "phishing"},
    {"subject": "Protect Your Online Accounts With Our Tool", "type": "phishing"},
    {"subject": "Update Your Payment Method to Avoid Late Fees", "type": "phishing"},
    {"subject": "Your Account Has Been Flagged for Review", "type": "phishing"},
    {"subject": "Act Now: Limited-Time Bonus Available", "type": "phishing"},
    {"subject": "Secure Your Account Before Midnight Tonight", "type": "phishing"},
    {"subject": "Congratulations! You’ve Been Approved for Credit", "type": "phishing"},
    {"subject": "Warning: Your Account May Be at Risk", "type": "phishing"},
    {"subject": "Protect Your Identity With Our New Service", "type": "phishing"},
    {"subject": "Important: Verify Your Address for Delivery", "type": "phishing"},
    {"subject": "You’ve Been Chosen for an Exclusive Offer", "type": "phishing"},
    {"subject": "Claim Your Free Gift Card in 3 Easy Steps", "type": "phishing"},
    {"subject": "Final Reminder: Update Your Account Details", "type": "phishing"},
    {"subject": "Secure Your Data With Our Latest Encryption Tool", "type": "phishing"},
    {"subject": "Earn $500 by Referring Your Friends Today", "type": "phishing"},
    {"subject": "Your Order Is Delayed: Provide More Details", "type": "phishing"},
    {"subject": "Unblock Your Account by Verifying Identity", "type": "phishing"},
    {"subject": "Win a Free Smartphone by Signing Up Today", "type": "phishing"},
    {"subject": "Protect Your Bank Account From Unauthorized Use", "type": "phishing"},
    {"subject": "Your Account May Be Closed: Act Now to Secure It", "type": "phishing"},
    {"subject": "Claim Your Free Trial Before It Expires", "type": "phishing"},
    {"subject": "Congratulations! You’ve Won a Shopping Spree", "type": "phishing"},
    {"subject": "Update Your Profile to Keep Using Our Services", "type": "phishing"},
    {"subject": "Act Now to Secure Your Data From Hackers", "type": "phishing"},
    {"subject": "Final Notice: Reactivate Your Account Today", "type": "phishing"},
    {"subject": "Your Credit Card Needs Urgent Verification", "type": "phishing"},
    {"subject": "Protect Your Computer From New Threats", "type": "phishing"},
    {"subject": "Exclusive Offer: Claim Your $500 Bonus", "type": "phishing"},
    {"subject": "Your Account Has Been Suspended: Verify Details", "type": "phishing"},
    {"subject": "Win Big by Entering Our Exclusive Sweepstakes", "type": "phishing"},
    {"subject": "Protect Your Email From Phishing Attacks Today", "type": "phishing"},
    {"subject": "Warning: Unusual Activity on Your Bank Account", "type": "phishing"},
    {"subject": "Your Account May Be Temporarily Locked", "type": "phishing"},
    {"subject": "Renew Your Subscription for Continued Access", "type": "phishing"},
    {"subject": "Action Required: Confirm Your Billing Address", "type": "phishing"},
    {"subject": "Claim Your Prize by Completing This Survey", "type": "phishing"},
    {"subject": "Final Reminder: Secure Your Account Now", "type": "phishing"},
    {"subject": "Congratulations! You’ve Won a New Laptop", "type": "phishing"},
    {"subject": "Your Payment of $499 Is Pending: Verify Details", "type": "phishing"},
    {"subject": "Act Now: Limited-Time Offer Ends Tonight", "type": "phishing"},
    {"subject": "Protect Your Data From Cyber Threats", "type": "phishing"},
    {"subject": "Your Subscription Renewal Is Due Soon", "type": "phishing"},
    {"subject": "Verify Your Account to Avoid Suspension", "type": "phishing"},
    {"subject": "Claim Your Reward Points Before They Expire", "type": "phishing"},
    {"subject": "Your Account Has Been Locked: Verify Identity", "type": "phishing"},
    {"subject": "Win Big by Completing This Quick Survey", "type": "phishing"},
    {"subject": "Congratulations! You’ve Been Selected for a Prize", "type": "phishing"},
    {"subject": "Protect Your Online Accounts With Our Tool", "type": "phishing"},
    {"subject": "Update Your Payment Method to Avoid Late Fees", "type": "phishing"},
    {"subject": "Your Account Has Been Suspended: Verify Now", "type": "spam"},
    {"subject": "Congratulations! You've Won a $10,000 Gift Card", "type": "spam"},
    {"subject": "Urgent: Reset Your Password to Secure Your Account", "type": "spam"},
    {"subject": "Act Now: Claim Your Unclaimed Funds", "type": "spam"},
    {"subject": "Verify Your Bank Details for Immediate Access", "type": "spam"},
    {"subject": "Notice of Legal Action Against You", "type": "spam"},
    {"subject": "You Have Been Shortlisted for a High-Paying Job", "type": "spam"},
    {"subject": "Final Notice: Lottery Winning Claim Expiring Soon", "type": "spam"},
    {"subject": "Charity Appeal: Help Disaster Victims Today", "type": "spam"},
    {"subject": "Your Computer Has Been Compromised: Fix It Now", "type": "spam"},
    {"subject": "Unusual Activity Detected on Your Account", "type": "spam"},
    {"subject": "Payment Required to Reactivate Subscription", "type": "spam"},
    {"subject": "Unlock Exclusive Benefits by Updating Your Details", "type": "spam"},
    {"subject": "Your Tax Refund Is Waiting: Click to Claim", "type": "spam"},
    {"subject": "Pay Outstanding Balance to Avoid Service Disruption", "type": "spam"},
    {"subject": "Your Social Media Account Has Been Flagged", "type": "spam"},
    {"subject": "Security Alert: Verify Identity to Avoid Suspension", "type": "spam"},
    {"subject": "Free iPhone 15 Pro for First 100 Respondents", "type": "spam"},
    {"subject": "Urgent: Confidential Document Needs Your Review", "type": "spam"},
    {"subject": "Claim Your Complimentary Vacation Package", "type": "spam"},
    {"subject": "Verify Your Purchase of [Expensive Item]", "type": "spam"},
    {"subject": "Action Required: Update Payment Information", "type": "spam"},
    {"subject": "Complete This Survey to Receive a $50 Gift Card", "type": "spam"},
    {"subject": "Important: Pay $200 to Remove Malware", "type": "spam"},
    {"subject": "Immediate Action Required: Verify Your Billing Address", "type": "spam"},
    {"subject": "You’ve Been Gifted a Free Cryptocurrency Token", "type": "spam"},
    {"subject": "Warning: Failed Login Attempt on Your Account", "type": "spam"},
    {"subject": "Congratulations! Your Loan Is Pre-Approved", "type": "spam"},
    {"subject": "Urgent Update: Suspicious Login Detected", "type": "spam"},
    {"subject": "Act Fast: Special Promotion Ends Tonight", "type": "spam"},
    {"subject": "Secure Your Bank Account Immediately", "type": "spam"},
    {"subject": "Limited-Time Offer: Upgrade to Premium Today", "type": "spam"},
    {"subject": "Your Parcel Is on Hold: Provide Details to Deliver", "type": "spam"},
    {"subject": "Exclusive Investment Opportunity Available Now", "type": "spam"},
    {"subject": "Urgent: Your Card Has Been Declined", "type": "spam"},
    {"subject": "Claim Your Free Antivirus Subscription", "type": "spam"},
    {"subject": "Your Online Banking Session Has Expired", "type": "spam"},
    {"subject": "Congratulations! You’ve Been Selected for a Prize", "type": "spam"},
    {"subject": "Subscription Renewal Required to Avoid Cancellation", "type": "spam"},
    {"subject": "Verify Your Account Ownership Immediately", "type": "spam"},
    {"subject": "Your Application Has Been Approved", "type": "spam"},
    {"subject": "Action Required: Update Security Information", "type": "spam"},
    {"subject": "Claim Your Free Vacation to Hawaii", "type": "spam"},
    {"subject": "Exclusive Offer: Earn $5,000 in a Month", "type": "spam"},
    {"subject": "Verify This Transaction: [$500 Payment]", "type": "spam"},
    {"subject": "Your PayPal Account Is at Risk", "type": "spam"},
    {"subject": "Download Invoice for Outstanding Payment", "type": "spam"},
    {"subject": "Thank You for Your Order: Payment Pending", "type": "spam"},
    {"subject": "Final Reminder: Upgrade Your Account Today", "type": "spam"},
    {"subject": "Secure Your Digital Wallet Now", "type": "spam"},
    {"subject": "Protect Your Account From Fraud: Verify Now", "type": "spam"},
    {"subject": "Special Reward Awaits: Claim Your Gift", "type": "spam"},
    {"subject": "Your Delivery Has Been Delayed: Update Address", "type": "spam"},
    {"subject": "Recover Lost Files With Our New Service", "type": "spam"},
    {"subject": "Important Update: Verify Before Midnight", "type": "spam"},
    {"subject": "Free Webinar: Learn How to Get Rich Quick", "type": "spam"},
    {"subject": "Your Account May Be Deactivated Soon", "type": "spam"},
    {"subject": "Last Chance: Claim Your Exclusive Bonus", "type": "spam"},
    {"subject": "Suspicious Activity Detected: Review Transaction", "type": "spam"},
    {"subject": "Earn $1,000 by Signing Up Today", "type": "spam"},
    {"subject": "Your Ticket to Financial Freedom Awaits", "type": "spam"},
    {"subject": "Confirm Your Email to Unlock Your Rewards", "type": "spam"},
    {"subject": "Payment Required: Renew Your Subscription Now", "type": "spam"},
    {"subject": "Activate Your Lifetime Warranty Immediately", "type": "spam"},
    {"subject": "Pay Outstanding Invoice to Avoid Late Fees", "type": "spam"},
    {"subject": "Immediate Action Needed: Verify Identity", "type": "spam"},
    {"subject": "You Have Been Selected for a Mystery Shopper Job", "type": "spam"},
    {"subject": "Unblock Your Account: Verify Login Activity", "type": "spam"},
    {"subject": "Congratulations! You’re Eligible for a Loan", "type": "spam"},
    {"subject": "Confirm Your Details to Avoid Account Suspension", "type": "spam"},
    {"subject": "Your Data Has Been Compromised: Download Fix", "type": "spam"},
    {"subject": "Claim Your Free Gift by Completing This Survey", "type": "spam"},
    {"subject": "Important: Update Your Tax Information", "type": "spam"},
    {"subject": "Your Prize Is Waiting: Act Now to Claim", "type": "spam"},
    {"subject": "Your Bank Account Requires Verification", "type": "spam"},
    {"subject": "Get 70% Off on Premium Services Today", "type": "spam"},
    {"subject": "Unusual Activity on Your Social Media Account", "type": "spam"},
    {"subject": "Confirm Your Attendance for Exclusive Event", "type": "spam"},
    {"subject": "You’ve Won a Trip to the Maldives!", "type": "spam"},
    {"subject": "Suspension Notice: Reactivate Your Account", "type": "spam"},
    {"subject": "Your Account Is Under Review: Verify Now", "type": "spam"},
    {"subject": "Your Credit Card Details Need Updating", "type": "spam"},
    {"subject": "Warning: Virus Detected on Your Device", "type": "spam"},
    {"subject": "You’ve Been Selected for a Business Opportunity", "type": "spam"},
    {"subject": "Action Required: Review Pending Payment", "type": "spam"},
    {"subject": "Your Free Subscription Ends Tomorrow", "type": "spam"},
    {"subject": "Claim $1,000 by Joining Our Program", "type": "spam"},
    {"subject": "Warning: Your Account May Be Hacked", "type": "spam"},
    {"subject": "Update Required to Secure Your Device", "type": "spam"},
    {"subject": "Special Offer Just for You: 90% Off", "type": "spam"},
    {"subject": "Free Trial Expires Today: Upgrade Now", "type": "spam"},
    {"subject": "Verify This Payment to Avoid Decline", "type": "spam"},
    {"subject": "Protect Your Account by Verifying Details", "type": "spam"},
    {"subject": "Complete Your Registration for a Free Gift", "type": "spam"},
    {"subject": "Your Social Security Number May Be Stolen", "type": "spam"},
    {"subject": "Win Big: Participate in Our Sweepstakes", "type": "spam"},
    {"subject": "Update Your Account Settings", "type": "spam"},
    {"subject": "Account Security Alert: Take Action Now", "type": "spam"},
    {"subject": "You've Won a Dream Vacation!", "type": "spam"},
    {"subject": "Urgent: Your Account is Compromised", "type": "spam"},
    {"subject": "Exclusive Offer: Limited Time Only", "type": "spam"},
    {"subject": "Claim Your Free Gift Card Now!", "type": "spam"},
    {"subject": "You're a Lucky Winner! Claim Your Prize", "type": "spam"},
    {"subject": "Last Chance: Get 50% Off Today", "type": "spam"},
    {"subject": "Your Bank Account is Under Review", "type": "spam"},
    {"subject": "Important Notice: Verify Your Identity", "type": "spam"},
    {"subject": "Limited Time Offer: Act Now!", "type": "spam"},
    {"subject": "Your Credit Card is Expiring Soon", "type": "spam"},
    {"subject": "You've Inherited a Fortune!", "type": "spam"},
    {"subject": "Urgent: Your Package is Held at Customs", "type": "spam"},
    {"subject": "Exclusive Access to Secret Deals", "type": "spam"},
    {"subject": "Your Account is Temporarily Suspended", "type": "spam"},
    {"subject": "You've Won a Free iPhone!", "type": "spam"},
    {"subject": "Limited Time Offer: Get Rich Quick", "type": "spam"},
    {"subject": "Urgent: Your Password Has Expired", "type": "spam"},
    {"subject": "Your Social Security Number is at Risk", "type": "spam"},
    {"subject": "You've Been Chosen for a Secret Mission", "type": "spam"},
    {"subject": "Claim Your Free Bitcoin Now!", "type": "spam"},
    {"subject": "Your Bank Account is Overdrawn", "type": "spam"},
    {"subject": "Urgent: Legal Notice - Immediate Action Required", "type": "spam"},
    {"subject": "You've Won a Luxury Car!", "type": "spam"},
    {"subject": "Your Account is About to Be Closed", "type": "spam"},
    {"subject": "Limited Time Offer: Get 90% Off", "type": "spam"},
    {"subject": "Urgent: Your Package is Held at Customs", "type": "spam"},
    {"subject": "Exclusive Access to Secret Deals", "type": "spam"},
    {"subject": "Your Account is Temporarily Suspended", "type": "spam"},
    {"subject": "You've Won a Free iPhone!", "type": "spam"},
    {"subject": "Limited Time Offer: Get Rich Quick", "type": "spam"},
    {"subject": "Urgent: Your Password Has Expired", "type": "spam"},
    {"subject": "Your Social Security Number is at Risk", "type": "spam"},
    {"subject": "You've Been Chosen for a Secret Mission", "type": "spam"},
    {"subject": "Claim Your Free Bitcoin Now!", "type": "spam"},
    {"subject": "Your Bank Account is Overdrawn", "type": "spam"},
    {"subject": "Urgent: Legal Notice - Immediate Action Required", "type": "spam"},
    {"subject": "You've Won a Luxury Car!", "type": "spam"},
    {"subject": "Your Account is About to Be Closed", "type": "spam"},
    {"subject": "Limited Time Offer: Get 90% Off", "type": "spam"}

]
    
     

sender_mails = [
    "john.doe@example.com",
    "support@banksecure.com",
    "customer.service@legitcompany.com",
    "admin@fakebankingalerts.com",
    "info@prizewinner.com",
    "contact@officialwebsite.com",
    "admin@securedaccountverify.com",
    "no-reply@socialmedia.com",
    "payment@online-shopper.com",
    "accounts@cryptocurrency-exchange.com",
    "info@scamphishingalert.com",
    "support@techsupportservices.com",
    "help@bankingverifications.com",
    "notifications@amazon.com",
    "admin@fraudalertservice.com",
    "congratulations@prizemoney.com",
    "update@subscriptionservice.com",
    "donations@charityfunds.org",
    "verify@paymentgateway.com",
    "service@officialgovernment.com",
    "contact@verifiedaccount.com",
    "admin@secure-banking.com",
    "info@free-trialservice.com",
    "no-reply@investmentspecialist.com",
    "customer.support@onlinehealthplan.com",
    "support@officialtravelagency.com",
    "alerts@fakeemailnotifications.com",
    "info@companyupdate.com",
    "service@confidentialbanking.com",
    "newsletter@legitsurveys.com",
    "team@tax-refund-service.com",
    "info@deliverytracking.com",
    "contact@job-offers.com",
    "admin@fakeaccountverification.com",
    "support@you-won-prize.com",
    "rewards@couponssavings.com",
    "customer.service@officialretailer.com",
    "billing@domain-renewal.com",
    "update@password-resetservice.com",
    "service@secure-techalert.com",
    "info@customerfeedbackemail.com",
    "help@phishing-verification.com",
    "support@antivirus-upgrade.com",
    "security@hackers-attempt.com",
    "winner@free-lottery.com",
    "no-reply@discountspecials.com",
    "contact@fakecreditloans.com",
    "admin@job-offer-scam.com",
    "info@securehealthinsurance.com",
    "support@cryptowalletservice.com",
    "notifications@fake-socialmediaupdate.com",
    "admin@lotteryscam.com",
    "team@expiringgiftcard.com",
    "support@online-fraud-protection.com",
    "alerts@alert-verify-email.com",
    "contact@update-account-info.com",
    "admin@fakegiftstore.com",
    "support@free-cryptocurrencycoins.com",
    "help@verify-your-transaction.com",
    "service@banking-security.com",
    "claim@legitcashoffers.com",
    "alerts@temporary-account-lock.com",
    "support@securepersonaldata.com",
    "info@accountupdate-now.com",
    "admin@falsesurveys.com",
    "contact@verify-identity.com",
    "admin@officialjobs.com",
    "newsletter@legitimatejoboffers.com",
    "support@warrantyupdate.com",
    "account-support@lockedaccounts.com",
    "service@free-onlinecourses.com",
    "team@secure-financialservices.com",
    "admin@tax-refundphishing.com",
    "support@websecurityupdate.com",
    "info@passwordresetverify.com",
    "contact@faketraveloffers.com",
    "service@malwarewarning.com",
    "alerts@phishing-attempt-notification.com",
    "security@bankingalertservice.com",
    "team@verified-businessoffers.com",
    "info@claim-your-free-vacation.com",
    "admin@account-resetalert.com",
    "contact@untrustedemailservice.com",
    "team@freeinvestmentsolutions.com",
    "support@fakecharitydonation.com",
    "info@secure-transactionsupport.com",
    "admin@fake-prizeservice.com",
    "support@maliciousdownloads.com",
    "service@urgentaccountverification.com",
    "alerts@taxrefundphishing.com",
    "support@phishing-claims.com",
    "admin@locked-bank-accounts.com",
    "security@counterfeitbankalerts.com",
    "info@travelreservecancellations.com",
    "help@scam-educationonline.com",
    "admin@fake-survey-scams.com",
    "support@malwarewarning.com",
    "service@legitcompany-prize.com",
    "info@secure-email-verification.com",
    "alerts@fake-securitybreach.com",
    "support@identity-protectionservice.com",
    "contact@secure-paymentalerts.com",
    "help@urgent-task-verification.com",
    "service@verify-newcreditcard.com",
    "team@financialfraudwatch.com",
    "contact@verify-paymentdetailsnow.com",
    "info@winner-claimed-prize.com",
    "alerts@fake-bankingalerts.com",
    "admin@fake-jobtraining.com",
    "support@identitytheftsolutions.com",
    "newsletter@secure-online-courses.com",
    "team@free-cryptowallet-service.com",
    "contact@passwordreset-verification.com",
    "info@lotterywinner.com",
    "alerts@banking-verifyservice.com",
    "support@confirmshipmentstatus.com",
    "admin@free-loanservice.com",
    "customer.service@secureinvestments.com",
    "service@jobapply-link.com",
    "info@account-notification.com",
    "alerts@loansubmissionverification.com",
    "contact@bankaccountupdate.com",
    "support@recovery-service-alert.com",
    "team@verify-fraudulentoffers.com",
    "admin@surveyfeedback-online.com",
    "alerts@legitpaymentverified.com",
    "security@software-updatealerts.com",
    "info@verify-passwordresetservice.com",
    "contact@important-mail-verification.com",
    "admin@secure-email-update.com",
    "support@fake-customerfeedback.com",
    "security@secure-financial-services.com",
    "info@critical-accountsecurity.com",
    "service@transaction-verification-service.com",
    "support@fake-giftcards.com",
    "admin@securepackageupdates.com",
    "contact@fraud-warning-system.com",
    "newsletter@financedepartment.com",
    "alerts@secure-transaction-confirmation.com",
    "info@updated-socialsecurityclaims.com",
    "admin@employment-benefitsalert.com",
    "service@win-cash-gift.com",
    "team@verificationalerts.com",
    "contact@secure-online-surveys.com",
    "alerts@personaldataalert.com",
    "info@you-won-prizeservice.com",
    "contact@urgent-claimservice.com",
    "security@account-suspensionalerts.com",
    "admin@fake-scholarshipprograms.com",
    "support@securetrackingdelivery.com",
    "alerts@subscriberserviceverify.com",
    "info@secured-offeravailable.com",
    "contact@update-paymentmethod.com",
    "admin@fraudulent-loanservice.com",
    "alerts@confirm-accountstatement.com",
    "team@winninglottery-verify.com",
    "service@account-lockedalerts.com",
    "support@verify-yourloaninfo.com",
    "info@securedmail-verification.com",
    "admin@account-suspensionupdate.com",
    "security@protect-youraccount.com",
    "info@phishingattempt-verify.com",
    "alerts@account-security-fraud.com"
]
receiver_mails = [
    "thales.smith@thales.com", "thales.johnson@thales.com", "thales.williams@thales.com",
    "thales.brown@thales.com", "thales.miller@thales.com", "thales.davis@thales.com",
    "thales.garcia@thales.com", "thales.martinez@thales.com", "thales.hernandez@thales.com",
    "thales.lopez@thales.com", "thales.gonzalez@thales.com", "thales.perez@thales.com",
    "thales.reyes@thales.com", "thales.sanchez@thales.com", "thales.rodriguez@thales.com",
    "thales.wilson@thales.com", "thales.moore@thales.com", "thales.taylor@thales.com",
    "thales.anderson@thales.com", "thales.jackson@thales.com", "thales.white@thales.com",
    "thales.harris@thales.com", "thales.clark@thales.com", "thales.lewis@thales.com",
    "thales.walker@thales.com", "thales.young@thales.com", "thales.king@thales.com",
    "thales.hill@thales.com", "thales.scott@thales.com", "thales.green@thales.com",
    "thales.adams@thales.com", "thales.baker@thales.com", "thales.nelson@thales.com",
    "thales.carter@thales.com", "thales.mitchell@thales.com", "thales.perry@thales.com",
    "thales.rose@thales.com", "thales.reed@thales.com", "thales.campbell@thales.com",
    "thales.patterson@thales.com", "thales.evans@thales.com", "thales.ward@thales.com",
    "thales.cook@thales.com", "thales.morris@thales.com", "thales.cooper@thales.com",
    "thales.bailey@thales.com", "thales.richardson@thales.com", "thales.hughes@thales.com",
    "thales.wood@thales.com", "thales.diaz@thales.com", "thales.ryan@thales.com",
    "thales.reynolds@thales.com", "thales.grant@thales.com", "thales.graham@thales.com",
    "thales.kelly@thales.com", "thales.sanders@thales.com", "thales.price@thales.com",
    "thales.russell@thales.com", "thales.james@thales.com", "thales.watson@thales.com",
    "thales.bennett@thales.com", "thales.hamilton@thales.com", "thales.foster@thales.com",
    "thales.sullivan@thales.com", "thales.murphy@thales.com", "thales.rogers@thales.com",
    "thales.perez@thales.com", "thales.reed@thales.com", "thales.wood@thales.com",
    "thales.martin@thales.com", "thales.ellis@thales.com", "thales.bell@thales.com",
    "thales.kelly@thales.com", "thales.lee@thales.com", "thales.alvarez@thales.com",
    "thales.jameson@thales.com", "thales.parker@thales.com", "thales.brown@thales.com",
    "thales.smith@thales.com", "thales.nichols@thales.com", "thales.garcia@thales.com",
    "thales.richards@thales.com", "thales.john@thales.com", "thales.douglas@thales.com",
    "thales.perry@thales.com", "thales.martinez@thales.com", "thales.baker@thales.com",
    "thales.miller@thales.com", "thales.davis@thales.com", "thales.martin@thales.com",
    "thales.kim@thales.com", "thales.brown@thales.com", "thales.james@thales.com",
    "thales.jenkins@thales.com", "thales.harris@thales.com", "thales.king@thales.com",
    "thales.crawford@thales.com", "thales.carter@thales.com", "thales.white@thales.com",
    "thales.morris@thales.com", "thales.evans@thales.com", "thales.reyes@thales.com",
    "thales.sanders@thales.com", "thales.ward@thales.com", "thales.jenkins@thales.com",
    "thales.nelson@thales.com", "thales.cameron@thales.com", "thales.lane@thales.com",
    "thales.jones@thales.com", "thales.parker@thales.com", "thales.murphy@thales.com",
    "thales.roberts@thales.com", "thales.perez@thales.com", "thales.sullivan@thales.com",
    "thales.lee@thales.com", "thales.mason@thales.com", "thales.hughes@thales.com",
    "thales.cameron@thales.com", "thales.richardson@thales.com", "thales.martinez@thales.com",
    "thales.ellis@thales.com", "thales.jones@thales.com", "thales.miller@thales.com",
    "thales.martin@thales.com", "thales.smith@thales.com", "thales.kelly@thales.com",
    "thales.wood@thales.com", "thales.simmons@thales.com", "thales.diaz@thales.com",
    "thales.grant@thales.com", "thales.rodriguez@thales.com", "thales.martin@thales.com",
    "thales.smith@thales.com", "thales.williams@thales.com", "thales.harris@thales.com",
    "thales.johnson@thales.com", "thales.moore@thales.com", "thales.green@thales.com",
    "thales.davis@thales.com", "thales.ryan@thales.com", "thales.king@thales.com",
    "thales.foster@thales.com", "thales.reynolds@thales.com", "thales.graham@thales.com",
    "thales.jackson@thales.com", "thales.sanders@thales.com", "thales.watson@thales.com",
    "thales.price@thales.com", "thales.lee@thales.com", "thales.hughes@thales.com",
    "thales.bennett@thales.com", "thales.murphy@thales.com", "thales.clark@thales.com",
    "thales.wood@thales.com", "thales.martin@thales.com", "thales.hill@thales.com",
    "thales.perry@thales.com", "thales.reed@thales.com", "thales.rodriguez@thales.com",
    "thales.smith@thales.com", "thales.white@thales.com", "thales.davis@thales.com",
    "thales.campbell@thales.com", "thales.morris@thales.com", "thales.green@thales.com",
    "thales.taylor@thales.com", "thales.brown@thales.com", "thales.jenkins@thales.com",
    "thales.ellis@thales.com", "thales.simmons@thales.com", "thales.martin@thales.com",
    "thales.ward@thales.com", "thales.carter@thales.com", "thales.smith@thales.com",
    "thales.jones@thales.com", "thales.harris@thales.com", "thales.rodriguez@thales.com",
    "thales.king@thales.com", "thales.baker@thales.com", "thales.sanders@thales.com",
    "thales.morris@thales.com", "thales.parker@thales.com", "thales.hughes@thales.com",
    "thales.wood@thales.com", "thales.johnson@thales.com", "thales.reynolds@thales.com",
    "thales.foster@thales.com", "thales.martinez@thales.com", "thales.miller@thales.com"]


date_list = [
    '2024/11/24', '2024/11/23', '2024/11/22', '2024/11/21', '2024/11/20', '2024/11/19', 
    '2024/11/18', '2024/11/17', '2024/11/16', '2024/11/15', '2024/11/14', '2024/11/13', 
    '2024/11/12', '2024/11/11', '2024/11/10', '2024/11/09', '2024/11/08', '2024/11/07', 
    '2024/11/06', '2024/11/05', '2024/11/04', '2024/11/03', '2024/11/02', '2024/11/01', 
    '2024/10/31', '2024/10/30', '2024/10/29', '2024/10/28', '2024/10/27', '2024/10/26', 
    '2024/10/25', '2024/10/24', '2024/10/23', '2024/10/22', '2024/10/21', '2024/10/20', 
    '2024/10/19', '2024/10/18', '2024/10/17', '2024/10/16', '2024/10/15', '2024/10/14', 
    '2024/10/13', '2024/10/12', '2024/10/11', '2024/10/10', '2024/10/09', '2024/10/08', 
    '2024/10/07', '2024/10/06', '2024/10/05', '2024/10/04', '2024/10/03', '2024/10/02', 
    '2024/10/01', '2024/09/30', '2024/09/29', '2024/09/28', '2024/09/27', '2024/09/26', 
    '2024/09/25', '2024/09/24', '2024/09/23', '2024/09/22', '2024/09/21', '2024/09/20', 
    '2024/09/19', '2024/09/18', '2024/09/17', '2024/09/16', '2024/09/15', '2024/09/14', 
    '2024/09/13', '2024/09/12', '2024/09/11', '2024/09/10', '2024/09/09', '2024/09/08', 
    '2024/09/07', '2024/09/06', '2024/09/05', '2024/09/04', '2024/09/03', '2024/09/02', 
    '2024/09/01', '2024/08/31', '2024/08/30', '2024/08/29', '2024/08/28', '2024/08/27', 
    '2024/08/26', '2024/08/25', '2024/08/24', '2024/08/23', '2024/08/22', '2024/08/21', 
    '2024/08/20', '2024/08/19', '2024/08/18', '2024/08/17', '2024/08/16', '2024/08/15', 
    '2024/08/14', '2024/08/13', '2024/08/12', '2024/08/11', '2024/08/10', '2024/08/09', 
    '2024/08/08', '2024/08/07', '2024/08/06', '2024/08/05', '2024/08/04', '2024/08/03', 
    '2024/08/02', '2024/08/01', '2024/07/31', '2024/07/30', '2024/07/29', '2024/07/28', 
    '2024/07/27', '2024/07/26', '2024/07/25', '2024/07/24', '2024/07/23', '2024/07/22', 
    '2024/07/21', '2024/07/20', '2024/07/19', '2024/07/18', '2024/07/17', '2024/07/16', 
    '2024/07/15', '2024/07/14', '2024/07/13', '2024/07/12', '2024/07/11', '2024/07/10', 
    '2024/07/09', '2024/07/08', '2024/07/07', '2024/07/06', '2024/07/05', '2024/07/04', 
    '2024/07/03', '2024/07/02', '2024/07/01', '2024/06/30', '2024/06/29', '2024/06/28', 
    '2024/06/27', '2024/06/26', '2024/06/25', '2024/06/24', '2024/06/23', '2024/06/22', 
    '2024/06/21', '2024/06/20', '2024/06/19', '2024/06/18', '2024/06/17', '2024/06/16', 
    '2024/06/15', '2024/06/14', '2024/06/13', '2024/06/12', '2024/06/11', '2024/06/10', 
    '2024/06/09', '2024/06/08', '2024/06/07', '2024/06/06', '2024/06/05', '2024/06/04', 
    '2024/06/03', '2024/06/02', '2024/06/01', '2024/05/31', '2024/05/30', '2024/05/29', 
    '2024/05/28', '2024/05/27', '2024/05/26', '2024/05/25', '2024/05/24', '2024/05/23', 
    '2024/05/22', '2024/05/21', '2024/05/20', '2024/05/19', '2024/05/18', '2024/05/17', 
    '2024/05/16', '2024/05/15', '2024/05/14', '2024/05/13', '2024/05/12', '2024/05/11', 
    '2024/05/10', '2024/05/09', '2024/05/08', '2024/05/07', '2024/05/06', '2024/05/05', 
    '2024/05/04', '2024/05/03', '2024/05/02', '2024/05/01', '2024/04/30', '2024/04/29', 
    '2024/04/28', '2024/04/27', '2024/04/26', '2024/04/25', '2024/04/24', '2024/04/23', 
    '2024/04/22', '2024/04/21', '2024/04/20', '2024/04/19', '2024/04/18', '2024/04/17', 
    '2024/04/16', '2024/04/15', '2024/04/14', '2024/04/13', '2024/04/12', '2024/04/11', 
    '2024/04/10', '2024/04/09', '2024/04/08', '2024/04/07', '2024/04/06', '2024/04/05', 
    '2024/04/04', '2024/04/03', '2024/04/02', '2024/04/01', '2024/03/31', '2024/03/30', 
    '2024/03/29', '2024/03/28']


